// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0

// Code generated by cmd_command_path_fallbacks; DO NOT EDIT.
// Source: internal/cli/command_path_fallbacks.json validated against the live Cobra tree.
// Regenerate with `make generate-schema` (or `go generate ./internal/cli`).

package cli

var generatedCommandPathFallbacks = []CommandPathFallback{
	{
		From:         "chat +chat-group-members",
		Mode:         "rewrite",
		To:           "chat +chat-members-list",
		Reviewed:     true,
		ReviewReason: "H10/H19 evaluation badcases repeatedly emitted +chat-group-members; +chat-members-list is the reviewed full group-member shortcut.",
	},
	{
		From:         "chat +chat-group-search",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "H12 evaluation badcase: +chat-group-search was invented while resolving a group; +chat-search is the unique equivalent shortcut.",
	},
	{
		From:         "chat +group-member-list",
		Mode:         "rewrite",
		To:           "chat +group-members",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +group-member-list for a group-name member lookup; +group-members is the unique reviewed read-only shortcut and canonical parameter validation remains authoritative.",
	},
	{
		From:         "chat +group-search",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation badcase: the model emitted +group-search with --query; +chat-search provides the same group-name search operation.",
	},
	{
		From:         "chat +group-send-text",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +send-to-group", "chat +messages-send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +group-send-text for a group text operation, but the invented name does not choose between name-resolved group text and the unified identifier-aware workflow; the write operation must not dispatch automatically.",
	},
	{
		From:         "chat +list-group-bots",
		Mode:         "rewrite",
		To:           "chat +chat-bots",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +list-group-bots for listing robots in one group; +chat-bots is the unique reviewed read-only shortcut. The fallback preserves flags and does not reinterpret generic IDs.",
	},
	{
		From:         "chat +list-robot",
		Mode:         "rewrite",
		To:           "chat +chat-bots",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted singular +list-robot for listing robots in one group; +chat-bots is the unique reviewed read-only shortcut. The fallback preserves flags and does not reinterpret generic IDs.",
	},
	{
		From:         "chat +list-robots",
		Mode:         "rewrite",
		To:           "chat +chat-bots",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +list-robots for listing robots in one group; +chat-bots is the unique reviewed read-only shortcut. The fallback preserves flags and does not reinterpret generic IDs.",
	},
	{
		From:         "chat +members",
		Mode:         "rewrite",
		To:           "chat +group-members",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation badcases emitted +members three times for listing members of a group selected by name; +group-members is the unique reviewed read-only shortcut for that intent.",
	},
	{
		From:         "chat +message-list",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +chat-messages", "chat +messages-list-direct", "chat +search-msg", "chat +unread-chats"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +message-list without identifying group versus direct history, conversation history versus cross-chat search, or ordinary versus unread conversations; no candidate may be selected automatically.",
	},
	{
		From:         "chat +read-single",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-list-direct", "chat +chat-messages"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +read-single six times for direct-message history, but the invented name does not choose between the focused direct-history shortcut and the broader group/direct history workflow; command recovery must stop before parameter validation or dispatch.",
	},
	{
		From:         "chat +rename-group",
		Mode:         "rewrite",
		To:           "chat +chat-update",
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +rename-group for the unique group-name update intent; +chat-update is the reviewed shortcut with that exact command-level operation. Parameter compatibility remains the canonical target's responsibility.",
	},
	{
		From:         "chat +search-group",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation badcase: the model emitted +search-group for group-name search; +chat-search is the exact reviewed shortcut and accepts the observed --keyword spelling.",
	},
	{
		From:         "chat +send",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat +dm", "chat +send-to-group"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send without a stable recipient type or sending identity; the write operation must stop until the caller chooses the unified, resolved-direct, or resolved-group workflow.",
	},
	{
		From:         "chat +send-by-bot",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat message send-by-bot"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-by-bot three times without a complete sending-identity contract; stop and present the unified identity-aware shortcut and the exact native bot sender instead of selecting a write path.",
	},
	{
		From:         "chat +send-dm",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +dm", "chat +messages-send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-dm twice, but the invented name does not choose between the resolved-name text shortcut and the unified identifier-aware sending workflow; the write operation must not dispatch automatically.",
	},
	{
		From:         "chat +send-file",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat message send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-file fifteen times with incompatible target and file parameter spellings; stop before dispatch and let the caller choose the unified shortcut or native current-user file workflow.",
	},
	{
		From:         "chat +send-image",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat message send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-image without proving whether the input is an existing mediaId or a local file; stop before dispatch and let the caller choose the reviewed unified or native workflow.",
	},
	{
		From:         "chat +send-media",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat message send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-media without a concrete media type, sending identity, or compatible parameter contract; stop before dispatch and let the caller choose the reviewed unified or native workflow.",
	},
	{
		From:         "chat +send-message",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat +dm", "chat +send-to-group"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-message without a stable recipient type or sending identity; the write operation must stop until the caller chooses the unified, resolved-direct, or resolved-group workflow.",
	},
	{
		From:         "chat +send-single",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +dm", "chat +messages-send"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-single for a direct message, but the invented name does not choose between the resolved-name text shortcut and the unified identifier-aware sending workflow; the write operation must not dispatch automatically.",
	},
	{
		From:         "chat +send-text",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat +dm", "chat +send-to-group"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation identified text content but not a stable recipient type or sending identity; the write operation must stop until the caller chooses the unified, resolved-direct, or resolved-group workflow.",
	},
	{
		From:         "chat +send-to",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +messages-send", "chat +dm", "chat +send-to-group"},
		Reviewed:     true,
		ReviewReason: "20260728 evaluation emitted +send-to without proving whether the recipient denotes a user, group, or low-level identifier; the write operation must not choose a target workflow automatically.",
	},
	{
		From:         "chat group search",
		Mode:         "rewrite",
		To:           "chat search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation report observed this non-runnable hint path 60 times; chat search is the exact native group-name search leaf.",
	},
	{
		From:         "oa +list-processes",
		Mode:         "ambiguous",
		Candidates:   []string{"oa +list-forms", "oa +my-initiated", "oa approval list-initiated"},
		Reviewed:     true,
		ReviewReason: "20260720 merged evaluation emitted +list-processes, but process can mean approval forms/templates or approval instances initiated by the current user; stop and present both shortcut workflows plus the exact native instance leaf.",
	},
}

func loadGeneratedCommandPathFallbacks() []CommandPathFallback {
	return generatedCommandPathFallbacks
}
