// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0

// Code generated by cmd_command_path_fallbacks; DO NOT EDIT.
// Source: internal/cli/command_path_fallbacks.json validated against the live Cobra tree.
// Regenerate with `make generate-schema` (or `go generate ./internal/cli`).

package cli

var generatedCommandPathFallbacks = []CommandPathFallback{
	{
		From:         "chat +chat-group-members",
		Mode:         "rewrite",
		To:           "chat +chat-members-list",
		Reviewed:     true,
		ReviewReason: "H10/H19 evaluation badcases repeatedly emitted +chat-group-members; +chat-members-list is the reviewed full group-member shortcut.",
	},
	{
		From:         "chat +chat-group-search",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "H12 evaluation badcase: +chat-group-search was invented while resolving a group; +chat-search is the unique equivalent shortcut.",
	},
	{
		From:         "chat +chat-list",
		Mode:         "ambiguous",
		Candidates:   []string{"chat +my-groups", "chat +chat-list-mine", "chat +chat-list-all", "chat +conversation-list"},
		Reviewed:     true,
		ReviewReason: "H12 evaluation badcase: chat-list does not identify whether the user wants joined groups, managed groups, every group, or all group/direct conversations.",
	},
	{
		From:         "chat +group-search",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation badcase: the model emitted +group-search with --query; +chat-search provides the same group-name search operation.",
	},
	{
		From:         "chat +search-group",
		Mode:         "rewrite",
		To:           "chat +chat-search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation badcase: the model emitted +search-group for group-name search; +chat-search is the exact reviewed shortcut and accepts the observed --keyword spelling.",
	},
	{
		From:         "chat group search",
		Mode:         "rewrite",
		To:           "chat search",
		Reviewed:     true,
		ReviewReason: "0803 evaluation report observed this non-runnable hint path 60 times; chat search is the exact native group-name search leaf.",
	},
}

func loadGeneratedCommandPathFallbacks() []CommandPathFallback {
	return generatedCommandPathFallbacks
}
