// Copyright 2026 Alibaba Group
// Licensed under the Apache License, Version 2.0 (the "License");

package cli

// reviewedRuntimeSchemaExclusionGroups is the reviewed authority for
// public Cobra leaves intentionally kept outside the stable Agent
// Schema surface. Exact path match only; no prefix or wildcard.
// Each group must be reviewed with a non-empty reason.
var reviewedRuntimeSchemaExclusionGroups = []runtimeSchemaExclusionGroup{
	{
		ID:       "cli-management",
		Reason:   "Local CLI lifecycle, authentication, configuration, recovery, and plugin-management commands are user-operated controls rather than stable Agent tools.",
		Reviewed: true,
		Commands: []string{
			"api",
			"auth export",
			"auth import",
			"auth login",
			"auth logout",
			"auth migrate-keychain",
			"auth reset",
			"auth status",
			"completion",
			"config list",
			"dev connect list",
			"dev connect restart",
			"doctor",
			"plugin build",
			"plugin config get",
			"plugin config list",
			"plugin config set",
			"plugin config unset",
			"plugin create",
			"plugin dev",
			"plugin disable",
			"plugin enable",
			"plugin info",
			"plugin install",
			"plugin list",
			"plugin remove",
			"plugin validate",
			"profile list",
			"profile switch",
			"profile use",
			"recovery execute",
			"recovery finalize",
			"recovery plan",
			"schema",
			"skill get",
			"skill install",
			"skill search",
			"skill setup",
			"upgrade",
			"version",
		},
	},
	{
		ID:       "agoal-out-of-surface",
		Reason:   "The Agoal product remains executable for compatibility but is outside the currently reviewed open-source Agent command surface.",
		Reviewed: true,
		Commands: []string{
			"agoal contract detail",
			"agoal contract fields",
			"agoal contract list",
			"agoal contract update",
			"agoal obj-template create-or-update",
			"agoal obj-template list",
			"agoal report list-statistics",
			"agoal report submit-detail",
			"agoal scorecard detail",
			"agoal scorecard entity-detail",
			"agoal scorecard update",
			"agoal strategy detail",
			"agoal strategy list",
			"agoal strategy update",
			"agoal user objectives",
			"agoal user rules",
		},
	},
	{
		ID:       "compatibility-helpers-pending-review",
		Reason:   "This executable compatibility/helper command has not yet completed stable interface, parameter, and Agent safety review; it must be reviewed before entering the release Catalog.",
		Reviewed: true,
		Commands: []string{
			"calendar acl add",
			"calendar acl delete",
			"calendar book update",
			"chat category add-conv",
			"chat category create",
			"chat category delete",
			"chat category remove-conv",
			"chat category rename",
			"chat chmod",
			"chat clear-all-red-point",
			"chat clear-messages",
			"chat clear-red-point",
			"chat data-auth cross-org",
			"chat group audit-join-validation",
			"chat group list-all",
			"chat group list-join-validations",
			"chat group members list-by-ids",
			"chat group notice create",
			"chat group notice edit",
			"chat group notice get",
			"chat group notice list",
			"chat group share-invite",
			"chat group update-alias",
			"chat hide",
			"chat list-all-conversations",
			"chat mark-read",
			"chat mark-unread",
			"chat message list-emotion-replies",
			"chat message set-top-msg",
			"chat message unset-top-msg",
			"chat mute-at-all",
			"chat mute-red-envelope",
			"chat text translate",
			"contact label get",
			"contact label list",
			"contact label list-members",
			"dev app version check-approval",
			"ding message list",
			"ding message recall-personal",
			"ding message receiver-status",
			"ding message send-by-message",
			"ding message send-personal",
			"mail allow-list add",
			"mail allow-list list",
			"mail allow-list remove",
			"mail auto-reply get",
			"mail auto-reply update",
			"mail block-list add",
			"mail block-list list",
			"mail block-list remove",
			"mail mailbox profile",
			"mail message batch-get",
			"mail message batch-update",
			"mail message verify",
			"mail rule adjust",
			"mail rule create",
			"mail rule delete",
			"mail rule list",
			"mail rule update",
			"mail sent-message recall",
			"mail sent-message recall-detail",
			"mail tag create",
			"mail tag delete",
			"mail tag update",
			"mail thread batch-trash",
			"mail thread batch-update",
			"mail thread list",
			"mail thread trash",
			"mail thread update",
			"oa approval append-task",
			"oa approval ding-info",
			"oa approval revert-activities",
			"oa approval revert-task",
			"oa approval search-forms",
			"todo task list-sub",
			"todo task remove-attachment",
		},
	},
	{
		ID:       "chat-shortcuts-pending-schema-curation",
		Reason:   "These reviewed public Chat shortcuts remain executable and discoverable through the Shortcut catalog while their typed Schema selection and metadata records are curated; exact paths keep reverse completeness strict without hiding future shortcuts.",
		Reviewed: true,
		Commands: []string{
			"chat +category-add-conversation",
			"chat +category-list-conversations",
			"chat +category-remove-conversation",
			"chat +chat-add-bot",
			"chat +chat-audit-join",
			"chat +chat-create",
			"chat +chat-list",
			"chat +chat-get-by-id",
			"chat +chat-members-get",
			"chat +chat-members-list",
			"chat +chat-mute-member",
			"chat +chat-quit",
			"chat +chat-remove-bot",
			"chat +chat-role-remove",
			"chat +chat-role-remove-user",
			"chat +chat-transfer-owner",
			"chat +chat-update",
			"chat +chat-update-icon",
			"chat +chat-update-settings",
			"chat +conversation-clear-messages",
			"chat +conversation-clear-red-point",
			"chat +conversation-hide",
			"chat +conversation-mark-read",
			"chat +conversation-mark-unread",
			"chat +conversation-mute",
			"chat +conversation-set-top",
			"chat +feed-group-query-item",
			"chat +flag-cancel",
			"chat +flag-create",
			"chat +flag-list",
			"chat +messages-add-emoji",
			"chat +messages-add-text-emotion",
			"chat +messages-batch-recall-by-bot",
			"chat +messages-batch-send-by-bot",
			"chat +messages-combine-forward",
			"chat +messages-create-text-emotion",
			"chat +messages-forward",
			"chat +messages-forward-topic",
			"chat +messages-list",
			"chat +messages-recall",
			"chat +messages-recall-by-bot",
			"chat +messages-remove-emoji",
			"chat +messages-remove-text-emotion",
			"chat +messages-reply",
			"chat +messages-resource-download",
			"chat +messages-resource-url",
			"chat +messages-send-by-bot",
			"chat +messages-set-pin",
			"chat +messages-set-top",
			"chat +messages-unset-pin",
			"chat +messages-unset-top",
		},
	},
}
